credentialsTab=Credentials
publicKeyLabel=Public Key
privateKeyLabel=Private Key
useExternalOrderMatchingLabel=Use Matching of External Orders

bookingModeLabel=Booking Mode
bookingModeChargeLabel=Immediate Charge
bookingModeAuthorizeLabel=Authorization (not available for all payment methods)