credentialsTab=Credentials
publicKeyLabel=Public Key
privateKeyLabel=Private Key
useExternalOrderMatchingLabel=Use Matching of External Orders
usePreOrderPage=Show Waiting page during checkout

bookingModeTab=Booking Modes

bookingModeLabel=Booking Mode
bookingModeChargeLabel=Immediate Charge
bookingModeAuthorizeLabel=Authorization

bookingModePaypalLabel=Booking Mode PayPal
bookingModeCardLabel=Booking Mode Card
bookingModeGooglePayLabel=Booking Mode Google Pay
bookingModeApplePayLabel=Booking Mode Apple Pay
bookingModeWeroLabel=Booking Mode Wero