paymentMethodName = "Unzer Payments"
paymentMethodDescription = "Plenty of payment methods"

paymentMethodName_alipay = "Alipay"
paymentMethodDescription_alipay = ""

paymentMethodName_applepay = "Apple Pay"
paymentMethodDescription_applepay = ""

paymentMethodName_bancontact = "Bancontact"
paymentMethodDescription_bancontact = ""

paymentMethodName_card = "Credit Card"
paymentMethodDescription_card = ""

paymentMethodName_eps = "EPS"
paymentMethodDescription_eps = ""

paymentMethodName_googlepay = "Google Pay"
paymentMethodDescription_googlepay = ""

paymentMethodName_ideal = "iDEAL"
paymentMethodDescription_ideal = ""

paymentMethodName_klarna = "Klarna"
paymentMethodDescription_klarna = ""

paymentMethodName_openbanking_pis = "Direct Bank Transfer"
paymentMethodDescription_openbanking_pis = ""

paymentMethodName_paypal = "PayPal"
paymentMethodDescription_paypal = ""

paymentMethodName_payu = "PayU"
paymentMethodDescription_payu = ""

paymentMethodName_post_finance_card = "PostFinance Card"
paymentMethodDescription_post_finance_card = ""

paymentMethodName_post_finance_efinance = "Post Finance eFinance"
paymentMethodDescription_post_finance_efinance = ""

paymentMethodName_przelewy24 = "Przelewy24"
paymentMethodDescription_przelewy24 = ""

paymentMethodName_paylater_direct_debit = "Direct Debit"
paymentMethodDescription_paylater_direct_debit = ""

paymentMethodName_paylater_invoice = "Invoice"
paymentMethodDescription_paylater_invoice = ""

paymentMethodName_paylater_installment = "Installment"
paymentMethodDescription_paylater_installment = ""

paymentMethodName_prepayment = "Prepayment"
paymentMethodDescription_prepayment = ""

paymentMethodName_sepa_direct_debit = "SEPA Direct Debit"
paymentMethodDescription_sepa_direct_debit = ""

paymentMethodName_sepa_direct_debit_secured = "SEPA Direct Debit Secured"
paymentMethodDescription_sepa_direct_debit_secured = ""

paymentMethodName_twint = "TWINT"
paymentMethodDescription_twint = ""

paymentMethodName_wechatpay = "WeChat Pay"
paymentMethodDescription_wechatpay = ""

accountHolder = "Account holder"
iban = "IBAN"
bic = "BIC"
paymentDescriptor = "Payment reference"