credentialsTab=Zugangsdaten
publicKeyLabel=Public Key
privateKeyLabel=Private Key
useExternalOrderMatchingLabel=Matching von externen Bestellungen verwenden
usePreOrderPage=Bitte-Warten-Seite anzeigen

bookingModeTab=Buchungsmodi

bookingModeLabel=Buchungsmodus
bookingModeChargeLabel=Sofortiger Zahlungseinzug
bookingModeAuthorizeLabel=Autorisierung

bookingModePaypalLabel=Buchungsmodus PayPal
bookingModeCardLabel=Buchungsmodus Karte
bookingModeGooglePayLabel=Buchungsmodus Google Pay
bookingModeApplePayLabel=Buchungsmodus Apple Pay
bookingModeWeroLabel=Buchungsmodus Wero