credentialsTab=Zugangsdaten
publicKeyLabel=Public Key
privateKeyLabel=Private Key
useExternalOrderMatchingLabel=Matching von externen Bestellungen verwenden

bookingModeLabel=Buchungsmodus
bookingModeChargeLabel=Sofortiger Zahlungseinzug
bookingModeAuthorizeLabel=Authorisierung (nicht für alle Zahlungsmethoden verfügbar)