payNow = "Jetzt bezahlen"

paymentMethodName = "Unzer Payments"
paymentMethodDescription = "Viele Zahlungsarten"

paymentMethodName_alipay = "Alipay"
paymentMethodDescription_alipay = ""

paymentMethodName_applepay = "Apple Pay"
paymentMethodDescription_applepay = ""

paymentMethodName_bancontact = "Bancontact"
paymentMethodDescription_bancontact = ""

paymentMethodName_card = "Kreditkarte"
paymentMethodDescription_card = ""

paymentMethodName_eps = "EPS"
paymentMethodDescription_eps = ""

paymentMethodName_googlepay = "Google Pay"
paymentMethodDescription_googlepay = ""

paymentMethodName_ideal = "iDEAL | Wero"
paymentMethodDescription_ideal = ""

paymentMethodName_klarna = "Klarna"
paymentMethodDescription_klarna = ""

paymentMethodName_openbanking_pis = "Direktüberweisung"
paymentMethodDescription_openbanking_pis = ""

paymentMethodName_paypal = "PayPal"
paymentMethodDescription_paypal = ""

paymentMethodName_payu = "PayU"
paymentMethodDescription_payu = ""

paymentMethodName_post_finance_card = "PostFinance Card"
paymentMethodDescription_post_finance_card = ""

paymentMethodName_post_finance_efinance = "Post Finance eFinance"
paymentMethodDescription_post_finance_efinance = ""

paymentMethodName_przelewy24 = "Przelewy24"
paymentMethodDescription_przelewy24 = ""

paymentMethodName_paylater_direct_debit = "Lastschrift"
paymentMethodDescription_paylater_direct_debit = ""

paymentMethodName_paylater_invoice = "Rechnung"
paymentMethodDescription_paylater_invoice = ""

paymentMethodName_paylater_installment = "Ratenzahlung"
paymentMethodDescription_paylater_installment = ""

paymentMethodName_prepayment = "Vorkasse"
paymentMethodDescription_prepayment = ""

paymentMethodName_sepa_direct_debit = "SEPA Lastschrift"
paymentMethodDescription_sepa_direct_debit = ""

paymentMethodName_twint = "TWINT"
paymentMethodDescription_twint = ""

paymentMethodName_wechatpay = "WeChat Pay"
paymentMethodDescription_wechatpay = ""

paymentMethodName_wero = "Wero"
paymentMethodDescription_wero = ""

accountHolder = "Kontoinhaber"
iban = "IBAN"
bic = "BIC"
paymentDescriptor = "Verwendungszweck"

generalError = "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es mit einer anderen Zahlungsart erneut."